defmodule DialyzerJson.MixProject do
  use Mix.Project

  @source_url "https://github.com/ZenHive/dialyzer_json"
  @version ".version" |> File.read!() |> String.trim()

  def project do
    [
      app: :dialyzer_json,
      version: @version,
      elixir: "~> 1.19",
      start_permanent: Mix.env() == :prod,
      deps: deps(),
      dialyzer: dialyzer(),
      description: description(),
      package: package(),
      source_url: @source_url,
      aliases: aliases()
    ]
  end

  def cli do
    [preferred_envs: ["dialyzer.json": :dev, "test.json": :test]]
  end

  defp dialyzer do
    [
      plt_add_apps: [:mix, :dialyzer, :dialyxir]
    ]
  end

  defp description do
    "AI-friendly JSON output for Dialyzer warnings. Structured output for Claude Code and similar AI editors."
  end

  defp package do
    [
      licenses: ["MIT"],
      links: %{"GitHub" => @source_url},
      # AGENTS.md is deliberately absent: it is generated by inlining the
      # maintainer's CLAUDE.md and its `@`-imports, so it carries contributor
      # workflow and references to unrelated internal projects. It stays in the
      # repo for the cross-family reviewer, but it is not consumer material and
      # must not ship inside the package tarball.
      files: ~w(lib .formatter.exs mix.exs .version README.md CHANGELOG.md LICENSE)
    ]
  end

  # Run "mix help compile.app" to learn about applications.
  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp aliases do
    [
      # Port 4022 — registry-assigned (~/.claude/tidewave-ports.md); 4002 collided with ccxt_extract
      tidewave: [
        "run --no-halt -e 'Agent.start(fn -> Bandit.start_link(plug: Tidewave, port: 4022) end)'"
      ]
    ]
  end

  # Run "mix help deps" to learn about dependencies.
  defp deps do
    [
      {:dialyxir, "~> 1.4", only: [:dev, :test], runtime: false},
      {:jason, "~> 1.4"},
      {:credo, "~> 1.7", only: [:dev, :test], runtime: false},
      {:sobelow, "~> 0.14", only: [:dev, :test], runtime: false},
      {:doctor, "~> 0.23", only: [:dev, :test], runtime: false},
      {:styler, "~> 1.11", only: [:dev, :test], runtime: false},
      {:ex_unit_json, "~> 0.5", only: [:dev, :test], runtime: false},
      {:reach, "~> 2.7", only: [:dev, :test], runtime: false},
      {:ex_ast, "~> 0.12.0", only: [:dev, :test], runtime: false},
      {:boxart, "~> 0.3.3", only: [:dev, :test], runtime: false},
      {:ex_doc, "~> 0.40", only: :dev, runtime: false},
      {:tidewave, "~> 0.5", only: :dev},
      {:bandit, "~> 1.12", only: :dev}
    ]
  end
end
